{
    "name": "Perfect Match QMS",
    "summary": "Unified Perfect Match QMS application shell and executive dashboard",
    "description": """
Perfect Match QMS provides the customer-facing application shell, dashboard,
and unified navigation for the reusable Perfect Match Digital QMS product.
Technical addons remain modular underneath this product entry point.
""",
    "version": "19.0.1.4.2",
    "category": "Operations/Quality",
    "author": "Perfect Match",
    "depends": [
        "mail",
        "pm_qms_core",
        "pm_qms_documents",
        "pm_qms_people",
        "pm_qms_evidence",
        "pm_qms_risk",
        "pm_qms_ncr",
        "pm_qms_capa",
        "pm_qms_audit",
        "pm_qms_kpi",
        "pm_qms_management_review",
        "pm_qms_implementation",
        "pm_qms_pack_quality",
        "pm_qms_migration",
        "pm_qms_calibration",
        "pm_qms_license",
    ],
    "data": [
        "data/assets.xml",
        "security/mission19_security.xml",
        "security/platform_security.xml",
        "security/ir.model.access.csv",
        "security/mission19_viewer_access.xml",
        "security/mission19_manager_access.xml",
        "security/mission23_framework_admin.xml",
        "views/shell_templates.xml",
        "views/dashboard_views.xml",
        "views/implementation_project_views.xml",
        "views/menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "pm_qms_app/static/src/scss/brand.scss",
            "pm_qms_app/static/src/xml/dashboard_button_box.xml",
            "pm_qms_app/static/src/js/dashboard_button_box.js",
            "pm_qms_app/static/src/js/dashboard_view.js",
            "pm_qms_app/static/src/js/customer_shell.js",
            "pm_qms_app/static/src/js/messaging_shell.js",
            "pm_qms_app/static/src/js/user_menu.js",
            "pm_qms_app/static/src/js/qms_history.js",
            "pm_qms_app/static/src/xml/qms_history.xml",
            "pm_qms_app/static/src/scss/qms_history.scss",
        ],
        "web.assets_frontend": [
            "pm_qms_app/static/src/scss/brand.scss",
        ],
    },
    "post_init_hook": "post_init_hook",
    "application": True,
    "installable": True,
    "license": "LGPL-3",
}
