from odoo import api, fields, models
from odoo.exceptions import ValidationError


class ProjectTask(models.Model):
    _inherit = "project.task"

    pm_implementation_project_id = fields.Many2one(
        "pm.qms.implementation.project",
        string="QMS Implementation Project",
        ondelete="set null",
        index=True,
        copy=False,
    )
    pm_implementation_control_id = fields.Many2one(
        "pm.qms.implementation.control",
        string="QMS Implementation Control",
        ondelete="set null",
        index=True,
        copy=False,
    )
    pm_control_instance_id = fields.Many2one(
        "pm.qms.control.instance",
        string="QMS Control Instance",
        ondelete="set null",
        index=True,
        copy=False,
    )
    pm_activity_id = fields.Many2one(
        "pm.qms.activity",
        string="Reusable QMS Activity",
        ondelete="set null",
        index=True,
        copy=False,
    )
    pm_generated = fields.Boolean(string="Generated By QMS", default=False, copy=False)
    pm_required = fields.Boolean(string="Required For Readiness", default=True, copy=False)

    _pm_generated_task_uniq = models.Constraint(
        "UNIQUE(pm_implementation_project_id, pm_implementation_control_id, pm_activity_id)",
        "A QMS implementation project can generate each activity task only once per control.",
    )

    @api.constrains(
        "pm_implementation_project_id",
        "pm_implementation_control_id",
        "pm_control_instance_id",
        "pm_activity_id",
        "project_id",
    )
    def _check_pm_relationships(self):
        for task in self.filtered("pm_generated"):
            implementation = task.pm_implementation_project_id
            line = task.pm_implementation_control_id
            if not implementation or not line or not task.pm_control_instance_id or not task.pm_activity_id:
                raise ValidationError("Generated QMS tasks must keep implementation, control, instance, and activity links.")
            if line.implementation_project_id != implementation:
                raise ValidationError("Generated task implementation control must belong to the same implementation project.")
            if task.pm_control_instance_id != line.control_instance_id:
                raise ValidationError("Generated task control instance must match the implementation control line.")
            if task.pm_activity_id.control_id != line.control_id:
                raise ValidationError("Generated task activity must belong to the same reusable control.")
            if task.project_id != implementation.odoo_project_id:
                raise ValidationError("Generated task Odoo project must match the implementation project.")
            if task.project_id.company_id and task.project_id.company_id != implementation.company_id:
                raise ValidationError("Generated task company must match the implementation company.")
