from . import customer_complaint
from . import quality_alert
from . import root_cause
from . import eight_d
from . import supplier_issue
from . import scar
from . import nonconformity
from . import capa
from . import dashboard
from . import management_review
from . import partner
